name: CI

on:
    push:
        branches:
            - 'feature/**'
            - 'bugfix/**'
            - main
            - develop
    pull_request: {}

jobs:
    phpunit:
        name: PHPUnit (PHP 8.3, SQLite)
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  extensions: mbstring, intl, pdo_mysql, pdo_sqlite, zip
                  coverage: none
                  tools: composer:v2

            - name: Cache Composer
              uses: actions/cache@v4
              with:
                  path: ~/.cache/composer/files
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install dependencies
              run: composer install --no-interaction --prefer-dist --no-progress

            # Optional: sicherstellen, dass das Test-Env geladen ist
            - name: Clear test cache
              run: php bin/console cache:clear --env=test --no-warmup

            - name: Run PHPUnit
              env:
                  APP_ENV: test
                  APP_DEBUG: 1
                  XDEBUG_MODE: off
                  # Falls du .env.test NICHT committen willst, könntest du hier alternativ direkt setzen:
                  # DATABASE_URL: 'sqlite:///%kernel.project_dir%/var/test.db'
              run: php bin/phpunit --display-deprecations

            - name: Build test schema
              run: php bin/console doctrine:schema:create --env=test
