# .github/workflows/ci.yml (auszugsweise, minimal & übersichtlich)
name: CI

on:
    push:
        branches: [ main, develop, 'feature/**', 'bugfix/**' ]
    pull_request:

jobs:
    phpunit:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  extensions: pdo_sqlite
                  coverage: none
                  ini-values: xdebug.mode=off   # unterdrückt die xdebug-Warnung

            - name: Install dependencies
              run: composer install --no-interaction --no-progress --prefer-dist

            - name: Prepare test env (SQLite)
              run: |
                  mkdir -p var
                  rm -f var/test.db                # frische Test-DB-Datei
                  php bin/console cache:clear --env=test

            - name: PHPUnit
              env:
                  APP_ENV: test
                  APP_DEBUG: 1
              run: vendor/bin/phpunit --colors=always
